### ISSUE TITLE
Изменился формат URL с составами

### ISSUE THREAD

**Issue by kalenkov** [old-bibigon/parse-cik#5]
В ГАС Выборы изменился формат URL с составами комиссий

было
http://www.vybory.izbirkom.ru/moscow_city/ik/4774108102204
стало
http://www.moscow_city.vybory.izbirkom.ru/region/moscow_city?action=ik&vrn=4774108102204

Изменения небольшие, но скрипт из-за этого перестал работать

**Comment by old-bibigon** [comment]
Не только это.
Поправил, но на всей стране не проверял
